kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "openstack-manila-csi.nodeplugin.fullname" . }}
  labels:
    app: {{ include "openstack-manila-csi.name" . }}
    chart: {{ include "openstack-manila-csi.chart" . }}
    component: nodeplugin
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "openstack-manila-csi.name" . }}
      component: nodeplugin
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "openstack-manila-csi.name" . }}
        chart: {{ include "openstack-manila-csi.chart" . }}
        component: nodeplugin
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "openstack-manila-csi.serviceAccountName.nodeplugin" . }}
      containers:
        - name: registrar
          image: "{{ .Values.csi.registrar.image.repository }}:{{ .Values.csi.registrar.image.tag }}"
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/{{ .Values.csi.plugin.driverName }}/csi.sock"
          lifecycle:
            preStop:
              exec:
                  command: [
                    "/bin/sh", "-c",
                    'rm -rf /registration/{{ .Values.csi.plugin.driverName }}
                  /registration/{{ .Values.csi.plugin.driverName }}-reg.sock'
                  ]
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.csi.registrar.image.pullPolicy }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources: {{ toYaml .Values.csi.registrar.resources | nindent 12 }}
        - name: nodeplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: "{{ .Values.csi.plugin.image.repository }}:{{ .Values.csi.plugin.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "-c",
            '/bin/manila-csi-plugin
            --v=5
            --nodeid=$(NODE_ID)
            --endpoint=$(CSI_ENDPOINT)
            --drivername={{ .Values.csi.plugin.driverName }}
            {{- range .Values.csi.plugin.nodeplugin.adapters }}
            --enable-adapter=name={{ .name }}{{ if .nodePluginEndpoint }},node-plugin-endpoint={{ printf "%s/%s" .nodePluginEndpoint.dir .nodePluginEndpoint.sockFile }}{{ end }}
            {{- end }}
            --mount-info-dir=/csi/mountinfo
            {{- if .Values.csi.plugin.runtimeConfig.enabled }}
            --runtime-config-file=/csi/runtimeconfig/runtimeconfig.json
            {{- end }}
            {{- if .Values.csi.plugin.topologyAwarenessEnabled }}
            --with-topology
            --nodeaz={{ .Values.csi.plugin.nodeAZ }}
            {{- end }}'
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: "unix:///var/lib/kubelet/plugins/{{ .Values.csi.plugin.driverName }}/csi.sock"
          imagePullPolicy: {{ .Values.csi.plugin.image.pullPolicy }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/{{ .Values.csi.plugin.driverName }}
            {{- if .Values.csi.plugin.runtimeConfig.enabled }}
            - name: runtime-config-dir
              mountPath: /csi/runtimeconfig
              readOnly: true
            {{- end }}
            {{- range .Values.csi.plugin.nodeplugin.adapters }}
            {{- if .nodePluginEndpoint }}
            - name: {{ .name }}-plugin-dir
              mountPath: {{ .nodePluginEndpoint.dir }}
            {{- end }}
            {{- end }}
            - name: mountinfo-dir
              mountPath: /csi/mountinfo
          resources: {{ toYaml .Values.csi.plugin.nodeplugin.resources | nindent 12 }}
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.csi.plugin.driverName }}
            type: DirectoryOrCreate
        {{- range .Values.csi.plugin.nodeplugin.adapters }}
        {{- if .nodePluginEndpoint }}
        - name: {{ .name }}-plugin-dir
          hostPath:
            path: {{ .nodePluginEndpoint.dir }}
            type: DirectoryOrCreate
        {{- end }}
        {{- end }}
        {{- if .Values.csi.plugin.runtimeConfig.enabled }}
        - name: runtime-config-dir
          configMap:
            name: manila-csi-runtimeconf-cm
        {{- end }}
        - name: mountinfo-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.csi.plugin.driverName }}/node/mountinfo
            type: DirectoryOrCreate
    {{- if .Values.csi.plugin.nodeplugin.affinity }}
      affinity: {{ toYaml .Values.csi.plugin.nodeplugin.affinity . | nindent 8 }}
    {{- end }}
    {{- if .Values.csi.plugin.nodeplugin.nodeSelector }}
      nodeSelector: {{ toYaml .Values.csi.plugin.nodeplugin.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.csi.plugin.nodeplugin.tolerations }}
      tolerations: {{ toYaml .Values.csi.plugin.nodeplugin.tolerations | nindent 8 }}
    {{- end }}
