nameOverride: ""
fullNameOverride: ""

csi:

  # manila-csi-plugin definition
  plugin:

    # Image spec
    image:
      repository: manila-csi-plugin-amd64
      pullPolicy: IfNotPresent
      tag: # defaults to .Chart.AppVersion

    # CSI Manila will be registered in the cluster under this name
    driverName: manila.csi.openstack.org

    # Set `topologyAwarenessEnabled` to true to enable topology awareness
    topologyAwarenessEnabled: false
    # If `topologyAwarenessEnabled` is set to true, `nodeAZ` will be used
    # as topology annotation for each node: topology.manila.csi.openstack.org=<nodeAZ>
    nodeAZ: "$(curl http://169.254.169.254/openstack/latest/meta_data.json | jq -r .availability_zone)"

    # Runtime configuration
    # If enabled, a ConfigMap named `manila-csi-runtimeconf-cm`
    # will be create and filled with `jsonData`.
    runtimeConfig:
      enabled: false
      # jsonData: |-
      #   {
      #     "nfs": {
      #       "matchExportLocationAddress": "172.168.122.0/24"
      #     }
      #   }

    # Definition for the controllerplugin component
    controllerplugin:

      # Enabled share adapters
      adapters:
        - name: nfs
        - name: cephfs
          nodePluginEndpoint:
            dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
            sockFile: csi.sock
          compatibility:
            createShareFromSnapshot:
              enabled: true
              # The associated node plugin must mount this path as a bi-directional mountpoint
              # on the node. The volume pointing to this path must be of the hostPath kind.
              # CSI CephFS mounts /var/lib/kubelet/plugins with bi-directional mount
              # propagation by default, we can take advantage of that:
              mountsDir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/node/mounts
              # See man page for rsync --timeout
              ioTimeout: 10
              # If set to true, error output from rsync will be redirected into
              # file "rsync-errors-<share name>.txt" on the destination share.
              # Otherwise, it will go into STDERR.
              stderrToFile: false

      # Active-passive high availability of CSI Manila's control plane is implemented using leader election.
      # The deployment uses Pod anti-affinity to spread the replicas to separate nodes of the cluster.
      # `replicas` specifies the number of control plane replicas to deploy.
      replicas: 1

      # Container resource constraints
      resources: {}

      # Scheduler settings
      nodeSelector: {}
      tolerations: []
      affinity: {}

    # Definition for the nodeplugin component
    nodeplugin:

      # Enabled share adapters
      adapters:
        - name: nfs
          # nodePluginEndpoint:
          #   dir: /var/lib/kubelet/plugins/csi-nfsplugin
          #   sockFile: csi.sock
        - name: cephfs
          nodePluginEndpoint:
            dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
            sockFile: csi.sock

      # Container resource constraints
      resources: {}

      # Scheduler settings
      nodeSelector: {}
      tolerations: []
      affinity: {}

    # Use fullnameOverride to fully override the name of this component
    # fullnameOverride: some-other-name

  # CSI node-driver-registrar sidecar container
  # See https://github.com/kubernetes-csi/node-driver-registrar for more info.
  registrar:

    # Image spec
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.1.0
      pullPolicy: IfNotPresent

    # Container resource constraints
    resources: {}

  # CSI external-provisioner sidecar container
  # See https://github.com/kubernetes-csi/external-provisioner for more info.
  provisioner:

    # Image spec
    image:
      repository: quay.io/k8scsi/csi-provisioner
      tag: v2.0.2
      pullPolicy: IfNotPresent

    # Container resource constraints
    resources: {}

  # CSI external-snapshotter sidecar container
  # See https://github.com/kubernetes-csi/external-snapshotter for more info.
  snapshotter:

    # Image spec
    image:
      repository: quay.io/k8scsi/csi-snapshotter
      tag: v2.1.1
      pullPolicy: IfNotPresent

    # Container resource constraints
    resources: {}

  # CSI external-resizer sidecar container
  # See https://github.com/kubernetes-csi/external-resizer
  resizer:

    # Image spec
    image:
      repository: quay.io/k8scsi/csi-resizer
      tag: v1.0.0
      pullPolicy: IfNotPresent

    # Container resource constraints
    resources: {}
