# Base name of the CSI Manila driver
driverName: manila.csi.openstack.org

# Enabled Manila share protocols
shareProtocols:
  - protocolSelector: NFS
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/csi-nfsplugin
      sockFile: csi.sock
  - protocolSelector: CEPHFS
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
      sockFile: csi.sock
    compatibilitySettings: "CreateShareFromSnapshotEnabled=true,CreateShareFromSnapshotCephFSMounts=/manila-cephfs-shares,CreateShareFromSnapshotCephFSLogErrorsToFile=true"

# Relevant for CEPHFS share protocol with CreateShareFromSnapshotEnabled=true compatibility setting:
# During snapshot recovery, CSI Manila may need to mount a blank CephFS share (via CSI CephFS).
# A bidirectional mount point for CephFS mounts must be specified in order to support CephFS snapshots.
# Must be identical to the path specified in CreateShareFromSnapshotCephFSMounts compatibility setting.
# Note that this path must be also mounted with bidirectional mount propagation in the CSI CephFS node plugin
# on the same node where CSI Manila's provisioner is running.
cephfsBidirectionalMountpoint: /manila-cephfs-shares

# CSI Manila image spec
csimanila:
  image:
    repository: manila-csi-plugin
    tag: latest
    pullPolicy: IfNotPresent

# DeamonSet deployment
nodeplugin:
  # Component name
  name: nodeplugin
  # CSI Manila container compute resources constraints
  nodeplugin:
    resources: {}
  # csi-node-driver-registrar
  registrar:
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.1.0
      pullPolicy: IfNotPresent
    resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Use fullnameOverride to fully override the name of this component
  # fullnameOverride: some-other-name

# StatefulSet deployment
controllerplugin:
  name: controllerplugin
  # CSI Manila container compute resources constraints
  nodeplugin:
    resources: {}
  # CSI external-provisioner container spec
  provisioner:
    image:
      repository: quay.io/k8scsi/csi-provisioner
      tag: v1.3.0
      pullPolicy: IfNotPresent
    resources: {}
  # CSI external-snapshotter container spec
  snapshotter:
    image:
      repository: quay.io/k8scsi/csi-snapshotter
      tag: v1.2.0
      pullPolicy: IfNotPresent
    resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Use fullnameOverride to fully override the name of this component
  # fullnameOverride: some-other-name

# Override the default app name using nameOverride
# nameOverride: some-other-name
